app/models.py
from . import db   

class Frutas(db.Model):
    __tablename__ = 'frutas'
    id = db.Column(db.Integer, primary_key=True)
    nome_fruta = db.Column(db.String(100), nullable=False)
    quantidade = db.Column(db.Integer, unique=True, nullable=False)
    cor = db.Column(db.String(100), nullable=False)
    data_aquisicao = db.Column(db.Date, nullable=True)
    categoria_id = db.Column(db.Integer, nullable=True)
    status = db.Column(db.Integer, nullable=True, default="1")

class Categorias(db.Model):
    __tablename__ = 'categorias'
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(50), nullable=False)




    

app/__init__.py
from flask import Flask
from datetime import timedelta
from flask_sqlalchemy import SQLAlchemy
import os
import json

#defini db como método SqlAlchemy 
db = SQLAlchemy()


#Cria a função para montar a aplicação e a retorna
def create_app():
    app = Flask(__name__, static_folder='static')   
    app.config["SECRET_KEY"] = "sddsfsfdfgg"
    #configuração banco dados SQLite
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:123456@localhost/quitanda'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(minutes=30)
    
    #Inicializa o metódo db para app
    db.init_app(app)
    
    #models
    from .models import Frutas, Categorias
    #Início: importamos e registramos o Blueprint
    from .routes.routes_main import bp
    app.register_blueprint(bp)
    #Fim: importamos e registramos o Blueprint    
    
    
    
    #Retorno da montagem do app
    return app    

    

app/routes/routes_main.py
from flask import Blueprint,jsonify, render_template, request, session, url_for, flash, redirect
from app.models import Frutas, Categorias
from werkzeug.utils import secure_filename
from datetime import datetime
from app import db
import os
import json


frutas = {
    
    1: {"nome_fruta":"Melancia","preco": 29.99,"quantidade":50},
    2: {"nome_fruta":"Pera","preco": 10,"quantidade":50},
    3: {"nome_fruta":"Uva","preco": 50,"quantidade":35},
    4: {"nome_fruta":"Laranja","preco": 35,"quantidade":30}
    
}

bp = Blueprint("main",__name__,template_folder='../templates/main')

@bp.route('/',endpoint='home')
def index():
    frutas = Frutas.query.all()
    return render_template("frutas.html",frutas=frutas)

@bp.route('/frutas/<int:id>', methods=['GET'])
def get_frutas(id):
    fruta = frutas.get(id)
    if fruta:
        return jsonify(fruta)
    return jsonify({"erro":"Frutas não encontrado"}),404

@bp.route('/categorias',endpoint='categorias')
def categorias():
    categorias = Categorias.query.all()
    return render_template("categorias.html", categorias=categorias)

@bp.route('/deletar',methods=['GET'], endpoint='deleta')
def deletarFruta():
    id = request.args.get('id')
    frutas = Frutas.query.get_or_404(id)    
    try:
        db.session.delete(frutas)
        db.session.commit()
        return redirect(url_for('main.home'))
    except Exception as e:
        db.session.rollback()
        return "Deu erro"
    
    
@bp.route('/atualizar/<int:id>',methods=['GET','POST'], endpoint='atualizar')
def atualizarFruta(id):
    categorias = Categorias.query.all()
    fruta = Frutas.query.get_or_404(id) 
    if request.method == 'POST':
         fruta.nome_fruta= request.form['nome_fruta']
         fruta.quantidade= request.form['quantidade']
         fruta.cor= request.form['cor']
         fruta.data_aquisicao= request.form['data_aquisicao']
         fruta.categoria_id= request.form['categoria_id']
         try:
            db.session.commit()
            flash('Fruta atualizado com sucesso!')
            return redirect(url_for('main.home'))
         except Exception as e:
            db.session.rollback()
            flash(f'Ocorreu um erro ao atualizar: {str(e)}')

    return render_template('editar_fruta.html', fruta=fruta, categorias=categorias)

@bp.route('/cadastro',endpoint='cadastro',methods=['GET','POST'])
def cadastro():
        categorias = Categorias.query.all()
        if request.method == 'POST':
            nome_fruta = request.form['nome_fruta']
            quantidade = request.form['quantidade']
            cor = request.form['cor']
            data_aquisicao = datetime.strptime(request.form['data_aquisicao'],'%Y-%m-%d').date()
            categoria_id= request.form['categoria_id']

            # Cria um novo usuário
            novo_fruta = Frutas(nome_fruta=nome_fruta, quantidade=quantidade, cor=cor, data_aquisicao=data_aquisicao, categoria_id=categoria_id)

            try:
                db.session.add(novo_fruta)
                db.session.commit()
                flash('Fruta cadastrada')
                return redirect(url_for('main.home'))
            except Exception as e:
                db.session.rollback()
                print(f'Ocorreu um erro ao cadastrar: {str(e)}') 
                    
        return render_template("cadastro.html",categorias=categorias)

ARQUIVO_FRUTAS = 'frutas.json'

def carregar_frutas():
    if os.path.exists(ARQUIVO_FRUTAS):
        with open(ARQUIVO_FRUTAS, 'r') as arquivo:
            return json.load(arquivo)
    else:
        with open(ARQUIVO_FRUTAS, 'w') as arquivo:
            json.dump({}, arquivo)
        return {}

def salvar_frutas():
    with open(ARQUIVO_FRUTAS, 'w') as arquivo:
        json.dump(frutasQuitanda, arquivo, indent=4)

frutasQuitanda = carregar_frutas()

bp = Blueprint("main", __name__, template_folder='../templates/main')

@bp.route('/api/fruta', endpoint='api', methods=['GET'])
def get_frutas():
    return jsonify(frutasQuitanda), 200

@bp.route('/api/post/fruta', methods=['POST'])
def criar_fruta():
    dados = request.get_json()
    novo_id = str(max([int(i) for i in frutasQuitanda.keys()]) + 1 if frutasQuitanda else 1)
    try:
        data_aquisicao = datetime.strptime(dados.get("data_aquisicao"), "%Y-%m-%d").date()
    except ValueError:
        return jsonify({"erro": "data de aquisição deve estar no formato YYYY-MM-DD"}), 400
    
    frutasQuitanda[novo_id] = {
        "nome_fruta": dados.get("nome_fruta"),
        "quantidade": dados.get("quantidade"),
        "cor": dados.get("cor"),
        "data_aquisicao": data_aquisicao.isoformat(),
        "categoria_id": dados.get("categoria_id"),
        "texto": "foi"
    }

    salvar_frutas()
    return jsonify(frutasQuitanda[novo_id]), 201
        

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/stilo.css') }}">

    <title>{% block titulo%} Página Inicial {% endblock %}</title>
</head>

<body>
    <main>
        <header>
            <div id="logo"><img src="{{ url_for('static', filename='img/logo.png') }}"></div>
            {% include "menu.html" %}
        </header>
        <article>
            {% block conteudo %}
            {% endblock %}
       </article>
    </main>
</body>

</html>

app/templates/cadastro.html
{% extends "base.html" %}

{% block conteudo %}
<form action="{{ url_for('main.cadastro') }}" method="POST" enctype="multipart/form-data">
    <div>
        <label>Nome da fruta</label>
        <input type="text" name="nome_fruta">
    </div>
    <div>
        <label>Quantidade</label>
        <input type="text" name="quantidade">
    </div>
    <div>
        <label>Cor</label>
        <input type="text" name="cor">
    </div>
    <div>
        <label>Data Aquisicao</label>
        <input type="date" name="data_aquisicao">
    </div>
    <div>
        <label>Categoria</label>
        <select name="categoria_id">
            {% for c in categorias %}

                <option value="{{c.id}}">{{c.nome}}</option>
            {% endfor%}

        </select>
    </div>
    <button type="submit">Salvar</button>
</form> 
{%endblock%}

app/templates/categorias.html
{% extends "base.html" %}

{% block conteudo %}
{% for c in categorias %}
<div class="bloco">
    <a href="">
        <main>
            <header>
                <div class="bolinha"></div>
            </header>
            <p class="titulo">{{c.nome}}</p>
            <div class="data_quantidade">

            </div>
        </main>
    </a>
</div>
{%endfor%}
{%endblock%}

app/templates/editar_fruta.html
{% extends "base.html" %}

{% block conteudo %}

<form method="POST" enctype="multipart/form-data">
    <div>
        <label>Nome da fruta</label>
        <input value="{{fruta.nome_fruta}}" type="text" name="nome_fruta">
    </div>
    <div>
        <label>Quantidade</label>
        <input value="{{fruta.quantidade}}" type="text" name="quantidade">
    </div>
    <div>
        <label>Cor</label>
        <input value="{{fruta.cor}}" type="text" name="cor">
    </div>
    <div>
        <label>Data Aquisicao</label>
        <input value="{{fruta.data_aquisicao}}" type="date" name="data_aquisicao">
    </div>
    <div>
        <label>Categoria</label>
        <select name="categoria_id">
            {% for c in categorias %}

                <option value="{{c.id}}">{{c.nome}}</option>
            {% endfor%}

        </select>
    </div>
    <button type="submit">Salvar</button>
</form> 

{%endblock%}

app/templates/frutas.html
{% extends "base.html" %}

{% block conteudo %}
{% for f in frutas %}
<div class="bloco cor">
  <main>
      <header>
        <a href="/deletar?id={{f.id}}"><div class="bolinha"></div></a>
        <a href="/atualizar/{{f.id}}"><div class="bolinha2"></div></a>
      </header>
      <p class="titulo">{{f.nome_fruta}}</p>
      <div class="data_quantidade">
          <div class="quantidade">
              <p class="claro">Quantidade</p>
              <p>{{f.quantidade}}</p>
          </div>
          <div class="data">
              <p class="claro">Data</p>
              <p>{{f.data_aquisicao}}</p>
          </div>
      </div>
  </main>
</div> 
{%endfor%}
{%endblock%}

app/templates/menu.html
<nav>
    <ul>
        <a href="{{ url_for('main.cadastro') }}">
            <li class="divisao">Cadastro</li>
        </a>
        <a href="{{ url_for('main.categorias') }}">
            <li class="divisao">Categorias</li>
        </a>
        <a href="{{ url_for('main.home') }}">
            <li>Catalogo</li>
        </a>
    </ul>
</nav>